### ISSUE TITLE
[DASHBOARD] Los campos de tipo string dejan ingresar datos tipo int

### ISSUE THREAD

**Issue by facundogp** [concurso-nosotros-queremos/frontend#10]
**Describe the bug**
los campos de tipo string dejan ingresar valores de tipo int 

**To Reproduce**
1.  ir a http://localhost:3000/dashboard
2.  ingresar numeros en campos que solo permitan letras
3.  ver bug
4.  no salta errores cuando se ingresa tipos de valores incorrectos 

**Screenshots**

**Desktop:**
 - OS: [windows 10]
 - Browser: [chrome]
 - Version: [Versión 76.0.3809.132 (Build oficial) (64 bits)

**Smartphone:**
 - Device: [HUAWEI GW metal]
 - Browser: [chrome]
 - Version: [Versión 76.0.3809.132 (Build oficial) (64 bits)

**Comment by profran** [comment]
Este es un problema de los esquemas de validación que venimos arrastrando hace varios sprints.
