### ISSUE TITLE
[INSCRIPCIONES] El contenedor del botón siguiente se superpone sobre los demás

### ISSUE THREAD

**Issue by TinchoOlivari** [concurso-nosotros-queremos/frontend#11]
**Describe the bug**
El formulario de inscripción tiene campos que pueden hacer variar la altura del contenedor padre. Cuando esto sucede, dichos campos se ven tapados por el contenedor del botón siguiente. Esto es debido a que "Siguiente" esta fixeado al fondo de la pagina.

**To Reproduce**
1. Ir http://localhost:3000/groups/add
2. En cualquier instancia del formulario
3. Rellenar con texto o enter para que los campos se hagan mas largos.
4. Hasta que pasen por debajo del contenedor siguiente
5. Intente scrollear para visibilizar estos campos, ahora ocultos.
6. No funciona. El scroll llega a cierto punto y después no baja mas. 

**Expected behavior**
Cuando los campos se extienden de manera vertical, el contenido que esta debajo debe seguir descendiendo.  Cuando dicho contenido llega y pasa por el contenedor de "Siguiente", debe ocultarse detras de este. Y cuando se scrollee para abajo se debe poder leer toda la informacion antes oculta por el contenedor..

**Screenshots**
![Captura](https://user-images.githubusercontent.com/19957702/64659714-91608600-d413-11e9-8022-94d84335375d.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 8.1 Pro
 - Browser Google Chrome
 - Version: Versión 76.0.3809.132 (Build oficial) (64 bits)

**Additional context**
Probablemente pase en movil.

**Comment by profran** [comment]
Hoy también me dí cuenta del problema cuando estaba probando el formulario en mobile.

Se me ocurren dos soluciones:
- El container se oculta onScroll, pero tendrías que scrollear de vuelta para arriba para que aparezcan(?
- El container del formulario se expande 100% - el height del container de los botones entonces podes scrollear para ver lo que queda debajo

**Comment by TinchoOlivari** [comment]
Solucionado!
