### ISSUE TITLE
[DASHBOARD] Campo dni no funciona correctamente

### ISSUE THREAD

**Issue by facundogp** [concurso-nosotros-queremos/frontend#3]
**Describe the bug**
campo dni tira error cuando inserto caracteres incorrectos, salta un error para corregirlo, inserto nuevamente bien los caracteres y una vez que envió el form(este se envía perfectamente en formato json en la bd del backend), no me deja agregar otro alumno, por mas que cambie el dni, tampoco me deja enviar otro form y figura como error el campo dni cuando en realidad esta bien hecho; si borro el alumno que estaba inscribiendo, y edito uno nuevo, el error ya figura, antes de que pueda introducir un carácter.

**To Reproduce**
1.  ir a http://localhost:3000/dashboard
2.  llenar los campos, e ingresar mal por primera vez el campo dni para que luego la pagina te 
     avise de que te equivocaste
3.  reescribir nuevamente el dni de forma correcta
4.  enviar el formulario del alumno inscrito
5.  ver el bug
6.  no poder agregar otro alumno
7.  borrar el alumno creado, para crear otro
8.  ver el bug
9.  el campo dni ya te figura como si hubieras introducido mal un carácter, cuando no se ha
     introducido  ningún carácter en los campos
10,1.  introducir nuevos datos en el nuevo alumno de forma correcta
11,1.  ver el bug
12,1.  no poder enviar el formulario nuevo
10,2.  introducir nuevos datos en el nuevo alumno de forma incorrecta
11,2.  los errores de que están mal puestos figuran
12,2.  corregirlos
13,2.  ver el bug
12,2.  no poder enviar el formulario nuevo

**Screenshots**
https://drive.google.com/file/d/1DwNjZyvzGE9G3M0sS5vnClTfgPQuSvIh/view?usp=sharing

**Desktop:**
 - OS: [windows 10] 
 - Browser: [chrome] 
 - Version:  [Versión 76.0.3809.132 (Build oficial) (64 bits)]

**Smartphone:**
 - Device: [HUAWEI GW metal]
 - OS: [andorid 7.0]
 - Browser: [chrome]
 - Version: [Versión 76.0.3809.132 (Build oficial) (64 bits)]

**Comment by TinchoOlivari** [comment]
Creo que aquí el error esta, en que, una vez tocado "Enviar" debería no haber posibilidad de modificar/agregar/borrar información previamente completada. 

**Posible solución:** El botón enviar redirecciona luego de ser clickeado.

**Comment by profran** [comment]
El problema esta en que el formulario se esta mandando con errores en el campo dni de los participantes. Cuando el backend responde al formulario con los errores que tiene, ese error se queda pegado y no te deja agregar otro participante porque hay errores de backend por debajo.

La solucion rapida es corregir los esquemas de validacion para que incluya el dni y no te deje mandar el formulario con errores en el dni.

Hay un problema mas grande que es como el formulario checkea si hay errores, que quedara para proximas iteraciones.

**Comment by TinchoOlivari** [comment]
Closed by WIP
