### ISSUE TITLE
[DASHBOARD] Evento del botón enviar no recetea el form para el próximo alumno a crear

### ISSUE THREAD

**Issue by facundogp** [concurso-nosotros-queremos/frontend#4]
**Describe the bug**
Cuando escribo el form de un alumno correctamente y aprieto el botón enviar, los datos se guardan en un json y se mandan a la bd del backend, pero luego  para añadir a otro alumno, tengo que volver atrás, hasta el primer paso del form y clickear el boton +

**To Reproduce**
1.   ir al http://localhost:3000/dashboard
2.   llenar el formulario
3.   clickear el boton enviar
4.   ver bug
5.   tener que volver para atrás hasta el primer paso del form
6.   tener que agregar un nuevo alumno de forma manual

**Screenshots**
https://drive.google.com/file/d/1AG6ehdcSSALfe8wFna2jsqruqN46AeNG/view?usp=sharing

**Desktop :**
 - OS: [windows 10]
 - Browser: [chrome]
 - Version: [Versión 76.0.3809.132 (Build oficial) (64 bits)]

**Smartphone :**
 - Device: [HUAWEI GW metal]
 - OS: [chrome]
 - Browser: [e.g. stock browser, safari]
 - Version: [Versión 76.0.3809.132 (Build oficial) (64 bits)]

**Comment by profran** [comment]
No entiendo bien el problema. Para aclarar, cualquier Bug que salga de querer enviar el formulario 2 o más veces seguidas va a ser descartada porque eso no va a pasar en la vida real. https://github.com/concurso-nosotros-queremos/frontend/issues/8#issuecomment-530175103

**Comment by TinchoOlivari** [comment]
WIP
