### ISSUE TITLE
[DASHBOARD] Despues de llenar los datos del 1° alumno, los demas forms que se crean se les quedan guardados los mismos datos del alumno anterior en los campos

### ISSUE THREAD

**Issue by facundogp** [concurso-nosotros-queremos/frontend#5]
**Describe the bug**
Una ve creado el primer alumno, y enviar los datos al backend, cuando se quiere crear otro alumno, se reestablecen en blanco UNICAMENTE los campos nombre, apellido y dni, en los demas campos quedan registrados los datos del form anterior y ademas por mas que se les cambie los datos, no se puede enviar otros form, porque el error ya viene pegado

**To Reproduce**
1.  ir a http://localhost:3000/dashboard
2.  ingresar datos en los campos
3.  enviar form 
4.  ver bug
5.  en todos los campos ya están guardados los datos del form anterior, a esepcion de los campos nobre, apellido y dni
6.  se ignora esto y se cambian los datos
7.  ver bug
8.  no deja enviar los demás form

**Screenshots**
https://drive.google.com/file/d/1ys7E3KXEoNysbKmI-0QmSiUbPjIeUUfw/view?usp=sharing

**Desktop:**
 - OS: [windows 10]
 - Browser: [chrome]
 - Version: [Versión 76.0.3809.132 (Build oficial) (64 bits)

**Smartphone:**
 - Device: [HUAWEI GW metal]
 - Browser: [chrome]
 - Version: [Versión 76.0.3809.132 (Build oficial) (64 bits)

**Comment by profran** [comment]
Esto es un Bug que se origina por como se manejan los errores internos y de back, cambiarlo es algo complejo pero se tiene que hacer

**Comment by TinchoOlivari** [comment]
Closed
