### ISSUE TITLE
[LANDING] Seleccionar texto en sección especifica de la pagina principal en Google Chrome devuelve error de cargar pagina 

### ISSUE THREAD

**Issue by ivangaitan** [concurso-nosotros-queremos/frontend#7]
**Describe el error**
Selecciono texto con el mouse y desplazo el movimiento del mismo hacia la izquierda o derecha y la pagina se cae automáticamente devolviendo un mensaje que describe error al cargar la pagina. 

**Reproducir**
Pasos para reproducir el comportamiento:
1. Vaya a 'https://cnq-frontend.herokuapp.com'
2. Haga clic en 'Proyectos'
3. Seleccione el texto de algún proyecto
4. Desplace el mouse hacia izquierda o derecha sin de-seleccionar el texto
5. Vea el error

**Comportamiento esperado**
Debería poder seleccionar texto y permanecer sin problemas en la misma.

**Escritorio (complete la siguiente información):**
 - SO: [Windows 10]
 - Navegador [Google Chrome]
 - Versión [Versión 76.0.3809.132 (Build oficial) (64 bits)]

**Contenido Adicional**
En Firefox no ocurre este error.
Solo ocurre en esta versión especifica de Google Chrome

**Comment by TinchoOlivari** [comment]
Es un problema de la librería, surge con la ultima actualización de Chrome. Entonces, podemos hacer lo siguiente, cambiar la librería, subir un issue al repo de la librería o usar elipsis con css. 
Creo que la mejor opción es usar css básico.

**Comment by TinchoOlivari** [comment]
Fixed! :) Librería removida.
