### ISSUE TITLE
Quedan registrados los errores que manda el backend en el dashboard

### ISSUE THREAD

**Issue by facundogp** [concurso-nosotros-queremos/frontend#8]
**Describe the bug**
cuando se llenan los datos en los campos del form de forma incorrecta y el dashboard te los reporta, se los cambia adecuadamente y se envía el form del alumno, pero al crear el siguiente form, ya quedan arrastrados los errores que tuviste marcados anteriormente en el form anterior.

**To Reproduce**
1.  ir a http://localhost:3000/dashboard
2.  ingresar los datos incorrectamente en los campos
3.  reportarte los errores
4.  corregirlos
5.  enviar form
6.  ver bug
7.  ya saltan los errores que te manda el backend, en los campos que ingresaste incorrectamente los datos del form anterior

**Screenshots**
https://drive.google.com/file/d/1Je3IXER4LyFJlcB7usHCbdiwBaSPlA4T/view?usp=sharing

**Desktop:**
 - OS: [windows 10]
 - Browser: [chrome]
 - Version: [Versión 76.0.3809.132 (Build oficial) (64 bits)

**Smartphone:**
 - Device: [HUAWEI GW metal]
 - Browser: [chrome]
 - Version: [Versión 76.0.3809.132 (Build oficial) (64 bits)

**Comment by profran** [comment]
Esto no sería un Bug. Mas adelante, cuando toques el botón enviar, la página te va a redireccionar a otra parte y el formulario se resetearía solo.

**Comment by profran** [comment]
Cierro la issue por ahora, si por alguna razón aceptamos la idea de que se puedan mandar más de una inscripción seguida este Bug va a aparecer de vuelta (lo dudo mucho).
