### ISSUE TITLE
[LANDING] Se encuentran errores de ortografía en todas las palabras de la pagina principal 

### ISSUE THREAD

**Issue by ivangaitan** [concurso-nosotros-queremos/frontend#9]
**Describe el error**
En la landing se puede observar que ninguna palabra posee uso de tildes correspondiente a su acentuación.

**Reproducir**
Pasos para reproducir el comportamiento:
1. Vaya a 'https://cnq-frontend.herokuapp.com'
2. Desplácese por toda la pagina
3. Observe los errores ortográficos

**Comportamiento esperado**
Desplazándome por toda la landing no debería encontrar ningún error ortográfico. 

**Contexto adicional**
Es independiente del dispositivo, sistema operativo y navegador.
Palabras:
Concurso anual de emprendimientos de alumn@s de los últimos años de la secundaria.

Ya tienes cuenta? Inicia Sesión

¿Cómo funciona?

Nosotros Queremos es un concurso anual de emprendimientos que apunta a despertar el espíritu emprendedor de los jóvenes en los últimos años de la secundaria.

La fundación válida y contesta al grupo

INSCRIBÍ A TU GRUPO

CONOCER MÁS

Acepto términos y condiciones

Fundación Inclusión Social

**Comment by TinchoOlivari** [comment]
Fixed by @facundogp
